CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    CONSTRAINT users_username_valid CHECK (
        username = lower(btrim(username))
        AND username ~ '^[a-z0-9_]{3,32}$'
    ),
    CONSTRAINT users_display_name_valid CHECK (
        display_name = btrim(display_name)
        AND char_length(display_name) BETWEEN 1 AND 100
    ),
    CONSTRAINT users_password_hash_valid CHECK (
        char_length(password_hash) BETWEEN 1 AND 512
    )
);

CREATE TABLE sessions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id TEXT NOT NULL,
    idle_expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sessions_device_id_valid CHECK (
        char_length(device_id) BETWEEN 1 AND 128
    ),
    CONSTRAINT sessions_expiry_valid CHECK (idle_expires_at > created_at),
    CONSTRAINT sessions_revocation_valid CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX sessions_user_id_created_at_idx ON sessions (user_id, created_at DESC);

CREATE INDEX sessions_user_id_device_id_idx ON sessions (user_id, device_id);

CREATE TABLE access_tokens (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    token_hash BYTEA NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT access_tokens_hash_valid CHECK (octet_length(token_hash) = 32),
    CONSTRAINT access_tokens_expiry_valid CHECK (expires_at > created_at)
);

CREATE INDEX access_tokens_session_id_idx ON access_tokens (session_id);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    parent_token_id BIGINT REFERENCES refresh_tokens(id) ON DELETE SET NULL,
    token_hash BYTEA NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT refresh_tokens_hash_valid CHECK (octet_length(token_hash) = 32),
    CONSTRAINT refresh_tokens_expiry_valid CHECK (expires_at > created_at),
    CONSTRAINT refresh_tokens_consumed_valid CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);

CREATE INDEX refresh_tokens_session_id_created_at_idx ON refresh_tokens (session_id, created_at DESC);

CREATE TABLE login_idempotency_results (
    request_id_hash BYTEA PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    encrypted_response BYTEA NOT NULL,
    nonce BYTEA NOT NULL,
    key_version INTEGER NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT login_idempotency_request_hash_valid CHECK (octet_length(request_id_hash) = 32),
    CONSTRAINT login_idempotency_expiry_valid CHECK (expires_at > created_at)
);

CREATE TABLE refresh_idempotency_results (
    refresh_token_id BIGINT PRIMARY KEY REFERENCES refresh_tokens(id) ON DELETE CASCADE,
    idempotency_key_hash BYTEA NOT NULL,
    encrypted_response BYTEA NOT NULL,
    nonce BYTEA NOT NULL,
    key_version INTEGER NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT refresh_idempotency_key_hash_valid CHECK (octet_length(idempotency_key_hash) = 32),
    CONSTRAINT refresh_idempotency_expiry_valid CHECK (expires_at > created_at)
);

CREATE TABLE conversations (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL DEFAULT 'direct',
    direct_user_low_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    direct_user_high_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    last_seq BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT conversations_kind_valid CHECK (kind IN ('direct', 'group')),
    CONSTRAINT conversations_last_seq_valid CHECK (last_seq >= 0),
    CONSTRAINT conversations_updated_at_valid CHECK (updated_at >= created_at),
    CONSTRAINT conversations_direct_pair_valid CHECK (
        (
            kind = 'direct'
            AND direct_user_low_id IS NOT NULL
            AND direct_user_high_id IS NOT NULL
            AND direct_user_low_id <= direct_user_high_id
        )
        OR (
            kind = 'group'
            AND direct_user_low_id IS NULL
            AND direct_user_high_id IS NULL
        )
    ),
    CONSTRAINT conversations_direct_pair_unique UNIQUE (
        direct_user_low_id,
        direct_user_high_id
    )
);

CREATE TABLE conversation_members (
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (conversation_id, user_id)
);

CREATE INDEX conversation_members_user_conversation_idx
    ON conversation_members (user_id, conversation_id);

CREATE TABLE messages (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id),
    conversation_seq BIGINT NOT NULL,
    sender_id BIGINT NOT NULL REFERENCES users(id),
    receiver_id BIGINT NOT NULL REFERENCES users(id),
    client_message_id TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT messages_client_message_id_valid CHECK (
        char_length(client_message_id) BETWEEN 16 AND 128
    ),
    CONSTRAINT messages_content_length_valid CHECK (
        char_length(content) BETWEEN 1 AND 4000
    ),
    CONSTRAINT messages_conversation_seq_valid CHECK (conversation_seq > 0),
    CONSTRAINT messages_conversation_seq_unique UNIQUE (conversation_id, conversation_seq),
    CONSTRAINT messages_sender_client_id_unique UNIQUE (sender_id, client_message_id)
);

CREATE INDEX messages_direction_history_idx
    ON messages (sender_id, receiver_id, created_at DESC, id DESC);

CREATE STATISTICS messages_sender_receiver_stats (dependencies, mcv)
    ON sender_id, receiver_id
    FROM messages;

ALTER STATISTICS messages_sender_receiver_stats SET STATISTICS 1000;

CREATE TABLE user_sync_counters (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    last_seq BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT user_sync_counters_last_seq_valid CHECK (last_seq >= 0)
);

CREATE TABLE user_message_events (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    seq BIGINT NOT NULL,
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, seq),
    CONSTRAINT user_message_events_seq_valid CHECK (seq > 0),
    CONSTRAINT user_message_events_message_unique UNIQUE (user_id, message_id)
);

CREATE INDEX user_message_events_message_id_idx
    ON user_message_events (message_id);

CREATE TABLE device_sync_states (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id TEXT NOT NULL,
    applied_seq BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, device_id),
    CONSTRAINT device_sync_states_device_id_valid CHECK (
        char_length(device_id) BETWEEN 1 AND 128
    ),
    CONSTRAINT device_sync_states_applied_seq_valid CHECK (applied_seq >= 0)
);

-- Legacy device_sync_states remains during the expand/contract rollout so an
-- old binary can drain version-3 Outbox events. New clients ACK per
-- conversation in this table.
CREATE TABLE device_conversation_sync_states (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id TEXT NOT NULL,
    conversation_id BIGINT NOT NULL,
    applied_seq BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, device_id, conversation_id),
    CONSTRAINT device_conversation_sync_states_membership_fk
        FOREIGN KEY (conversation_id, user_id)
        REFERENCES conversation_members(conversation_id, user_id)
        ON DELETE CASCADE,
    CONSTRAINT device_conversation_sync_states_device_id_valid CHECK (
        char_length(device_id) BETWEEN 1 AND 128
    ),
    CONSTRAINT device_conversation_sync_states_applied_seq_valid CHECK (applied_seq >= 0)
);

CREATE TABLE outbox_events (
    event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type TEXT NOT NULL,
    payload_version SMALLINT NOT NULL,
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    payload JSONB NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_until TIMESTAMPTZ,
    lock_token UUID,
    ready_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    dead_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT outbox_event_type_valid CHECK (char_length(event_type) BETWEEN 1 AND 100),
    CONSTRAINT outbox_payload_version_valid CHECK (payload_version > 0),
    CONSTRAINT outbox_attempt_count_valid CHECK (attempt_count >= 0),
    CONSTRAINT outbox_next_attempt_valid CHECK (next_attempt_at >= created_at),
    CONSTRAINT outbox_lock_pair_valid CHECK ((locked_until IS NULL) = (lock_token IS NULL)),
    CONSTRAINT outbox_ready_time_valid CHECK (ready_at IS NULL OR ready_at >= created_at),
    CONSTRAINT outbox_published_time_valid CHECK (published_at IS NULL OR published_at >= created_at),
    CONSTRAINT outbox_dead_time_valid CHECK (dead_at IS NULL OR dead_at >= created_at),
    CONSTRAINT outbox_single_terminal_state CHECK (published_at IS NULL OR dead_at IS NULL),
    CONSTRAINT outbox_message_publish_requires_ready CHECK (
        event_type <> 'message.created' OR published_at IS NULL OR ready_at IS NOT NULL
    ),
    CONSTRAINT outbox_last_error_valid CHECK (last_error IS NULL OR char_length(last_error) <= 2000),
    CONSTRAINT outbox_message_event_unique UNIQUE (message_id, event_type)
);

CREATE INDEX outbox_pending_idx
    ON outbox_events (next_attempt_at, created_at, event_id)
    WHERE published_at IS NULL AND dead_at IS NULL;

CREATE TABLE message_projection_jobs (
    event_id UUID NOT NULL REFERENCES outbox_events(event_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    shard SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    projected_at TIMESTAMPTZ,
    PRIMARY KEY (event_id, user_id),
    CONSTRAINT message_projection_jobs_shard_valid CHECK (shard BETWEEN 0 AND 255),
    CONSTRAINT message_projection_jobs_user_message_unique UNIQUE (user_id, message_id)
);

CREATE INDEX message_projection_jobs_pending_shard_idx
    ON message_projection_jobs (shard, created_at, message_id, user_id)
    WHERE projected_at IS NULL;

CREATE INDEX outbox_unready_message_projection_idx
    ON outbox_events (created_at, event_id)
    WHERE event_type = 'message.created'
      AND ready_at IS NULL
      AND published_at IS NULL
      AND dead_at IS NULL;

CREATE TABLE outbox_recipients (
    event_id UUID NOT NULL REFERENCES outbox_events(event_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    cursor BIGINT NOT NULL,
    PRIMARY KEY (event_id, user_id),
    CONSTRAINT outbox_recipients_cursor_valid CHECK (cursor > 0),
    CONSTRAINT outbox_recipients_user_cursor_unique UNIQUE (user_id, cursor),
    CONSTRAINT outbox_recipients_sync_event_fk
        FOREIGN KEY (user_id, cursor)
        REFERENCES user_message_events(user_id, seq)
        ON DELETE CASCADE
);
