BEGIN;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

INSERT INTO users (id, name)
SELECT user_id, 'user-' || user_id
FROM (
    SELECT sender_id AS user_id FROM messages
    UNION
    SELECT receiver_id AS user_id FROM messages
) AS message_users
ORDER BY user_id;

SELECT setval(
    pg_get_serial_sequence('users', 'id'),
    COALESCE((SELECT MAX(id) FROM users), 1),
    EXISTS (SELECT 1 FROM users)
);

ALTER TABLE messages
    ADD CONSTRAINT messages_sender_id_fkey
        FOREIGN KEY (sender_id) REFERENCES users(id),
    ADD CONSTRAINT messages_receiver_id_fkey
        FOREIGN KEY (receiver_id) REFERENCES users(id);

COMMIT;
