package migrate

import (
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// schemaFingerprintQuery describes the public application schema while
// intentionally ignoring object names generated by PostgreSQL and physical
// column order. Each row is a canonical JSON value; ordering and hashing happen
// in SQL so the result is stable across connections.
const schemaFingerprintQuery = `
WITH schema_objects AS (
    SELECT jsonb_build_array(
               'table', relation.relname, relation.relpersistence,
               relation.relkind, relation.relrowsecurity, relation.relforcerowsecurity
           )::text AS signature
    FROM pg_class AS relation
    JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
    WHERE namespace.nspname = 'public'
      AND relation.relkind IN ('r', 'p')
      AND relation.relname <> 'schema_migrations'

    UNION ALL

    SELECT jsonb_build_array(
               'column', relation.relname, attribute.attname,
               format_type(attribute.atttypid, attribute.atttypmod),
               attribute.attnotnull, attribute.attidentity, attribute.attgenerated,
               pg_get_expr(default_value.adbin, default_value.adrelid, true),
               CASE WHEN attribute.attcollation = type_data.typcollation
                    THEN NULL ELSE collation_data.collname END
           )::text
    FROM pg_attribute AS attribute
    JOIN pg_class AS relation ON relation.oid = attribute.attrelid
    JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
    JOIN pg_type AS type_data ON type_data.oid = attribute.atttypid
    LEFT JOIN pg_attrdef AS default_value
           ON default_value.adrelid = attribute.attrelid
          AND default_value.adnum = attribute.attnum
    LEFT JOIN pg_collation AS collation_data ON collation_data.oid = attribute.attcollation
    WHERE namespace.nspname = 'public'
      AND relation.relkind IN ('r', 'p')
      AND relation.relname <> 'schema_migrations'
      AND attribute.attnum > 0
      AND NOT attribute.attisdropped

    UNION ALL

    SELECT jsonb_build_array(
               'constraint', relation.relname, constraint_data.contype,
               pg_get_constraintdef(constraint_data.oid, true)
           )::text
    FROM pg_constraint AS constraint_data
    JOIN pg_class AS relation ON relation.oid = constraint_data.conrelid
    JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
    WHERE namespace.nspname = 'public'
      AND relation.relname <> 'schema_migrations'
	  AND (constraint_data.contype <> 'u' OR constraint_data.condeferrable)

    UNION ALL

	-- A non-deferrable UNIQUE constraint and its equivalent standalone UNIQUE
	-- index enforce the same invariant used by this application. Normalize both
	-- to the same signature; deferrable constraints remain distinct above.
    SELECT jsonb_build_array(
               'index', table_relation.relname, access_method.amname,
               true, index_data.indisvalid, index_data.indisready,
               index_data.indnullsnotdistinct,
               (SELECT jsonb_agg(jsonb_build_array(
                           key_position <= index_data.indnkeyatts,
                           pg_get_indexdef(index_data.indexrelid, key_position, true)
                       ) ORDER BY key_position)
                FROM generate_series(1, index_data.indnatts) AS key_position),
               pg_get_expr(index_data.indpred, index_data.indrelid, true)
           )::text
    FROM pg_constraint AS constraint_data
    JOIN pg_index AS index_data ON index_data.indexrelid = constraint_data.conindid
    JOIN pg_class AS table_relation ON table_relation.oid = constraint_data.conrelid
    JOIN pg_namespace AS namespace ON namespace.oid = table_relation.relnamespace
    JOIN pg_class AS index_relation ON index_relation.oid = index_data.indexrelid
    JOIN pg_am AS access_method ON access_method.oid = index_relation.relam
    WHERE namespace.nspname = 'public'
      AND table_relation.relname <> 'schema_migrations'
	  AND constraint_data.contype = 'u'
	  AND NOT constraint_data.condeferrable

    UNION ALL

    SELECT jsonb_build_array(
               'index', table_relation.relname, access_method.amname,
               index_data.indisunique, index_data.indisvalid, index_data.indisready,
               index_data.indnullsnotdistinct,
               (SELECT jsonb_agg(jsonb_build_array(
                           key_position <= index_data.indnkeyatts,
                           pg_get_indexdef(index_data.indexrelid, key_position, true)
                       ) ORDER BY key_position)
                FROM generate_series(1, index_data.indnatts) AS key_position),
               pg_get_expr(index_data.indpred, index_data.indrelid, true)
           )::text
    FROM pg_index AS index_data
    JOIN pg_class AS table_relation ON table_relation.oid = index_data.indrelid
    JOIN pg_namespace AS namespace ON namespace.oid = table_relation.relnamespace
    JOIN pg_class AS index_relation ON index_relation.oid = index_data.indexrelid
    JOIN pg_am AS access_method ON access_method.oid = index_relation.relam
    WHERE namespace.nspname = 'public'
      AND table_relation.relname <> 'schema_migrations'
      AND NOT EXISTS (
          SELECT 1 FROM pg_constraint AS constraint_data
          WHERE constraint_data.conindid = index_data.indexrelid
      )

    UNION ALL

    SELECT jsonb_build_array(
               'statistics', table_relation.relname, statistics_data.stxkind,
               statistics_data.stxstattarget,
               (SELECT jsonb_agg(attribute.attname ORDER BY key_data.ordinality)
                FROM unnest(statistics_data.stxkeys) WITH ORDINALITY AS key_data(attnum, ordinality)
                JOIN pg_attribute AS attribute
                  ON attribute.attrelid = statistics_data.stxrelid
                 AND attribute.attnum = key_data.attnum),
               pg_get_expr(statistics_data.stxexprs, statistics_data.stxrelid, true)
           )::text
    FROM pg_statistic_ext AS statistics_data
    JOIN pg_class AS table_relation ON table_relation.oid = statistics_data.stxrelid
    JOIN pg_namespace AS namespace ON namespace.oid = statistics_data.stxnamespace
    WHERE namespace.nspname = 'public'
      AND table_relation.relname <> 'schema_migrations'

    UNION ALL

    SELECT jsonb_build_array(
               'sequence', table_relation.relname, attribute.attname,
               sequence_data.seqtypid::regtype::text, sequence_data.seqstart,
               sequence_data.seqincrement, sequence_data.seqmax,
               sequence_data.seqmin, sequence_data.seqcache, sequence_data.seqcycle
           )::text
    FROM pg_sequence AS sequence_data
    JOIN pg_class AS sequence_relation ON sequence_relation.oid = sequence_data.seqrelid
    JOIN pg_depend AS dependency
      ON dependency.classid = 'pg_class'::regclass
     AND dependency.objid = sequence_relation.oid
     AND dependency.deptype IN ('a', 'i')
    JOIN pg_class AS table_relation ON table_relation.oid = dependency.refobjid
    JOIN pg_namespace AS namespace ON namespace.oid = table_relation.relnamespace
    JOIN pg_attribute AS attribute
      ON attribute.attrelid = table_relation.oid
     AND attribute.attnum = dependency.refobjsubid
    WHERE namespace.nspname = 'public'
      AND table_relation.relname <> 'schema_migrations'

    UNION ALL

    SELECT jsonb_build_array(
               'view', relation.relname, pg_get_viewdef(relation.oid, true)
           )::text
    FROM pg_class AS relation
    JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
    WHERE namespace.nspname = 'public'
      AND relation.relkind IN ('v', 'm')
)
SELECT signature
FROM schema_objects
ORDER BY signature`

// ExpectedSchemaFingerprint015 is filled from a fresh database produced by
// migrations 001 through 015. A later migration needs its own reviewed target.
const ExpectedSchemaFingerprint015 = "a7cf0ed182ff73a68fdfac8c90dce4138d91c2ebfb03f313c91556abd8ed7462"

func SchemaFingerprint(ctx context.Context, queryer interface {
	Query(context.Context, string, ...any) (pgx.Rows, error)
}) (string, int, error) {
	signatures, err := SchemaSignatures(ctx, queryer)
	if err != nil {
		return "", 0, err
	}
	hash := sha256.New()
	for _, signature := range signatures {
		_, _ = hash.Write([]byte(signature))
		_, _ = hash.Write([]byte{'\n'})
	}
	return fmt.Sprintf("%x", hash.Sum(nil)), len(signatures), nil
}

func SchemaSignatures(ctx context.Context, queryer interface {
	Query(context.Context, string, ...any) (pgx.Rows, error)
}) ([]string, error) {
	rows, err := queryer.Query(ctx, schemaFingerprintQuery)
	if err != nil {
		var postgresError *pgconn.PgError
		if errors.As(err, &postgresError) {
			return nil, fmt.Errorf("read schema fingerprint at SQL position %d: %w", postgresError.Position, err)
		}
		return nil, fmt.Errorf("read schema fingerprint: %w", err)
	}
	defer rows.Close()

	var signatures []string
	for rows.Next() {
		var signature string
		if err := rows.Scan(&signature); err != nil {
			return nil, fmt.Errorf("scan schema fingerprint: %w", err)
		}
		signatures = append(signatures, strings.TrimSpace(signature))
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate schema fingerprint: %w", err)
	}
	return signatures, nil
}
